name: OpenDTU-OnBattery Build
on:
  push:
    paths-ignore:
      - docs/**
      - '**/*.md'
    branches:
      - main
    tags-ignore:
      - '**'
  pull_request:
    paths-ignore:
      - docs/**
      - '**/*.md'
  workflow_dispatch:

jobs:
  get_default_envs:
    name: Gather Environments
    runs-on: ubuntu-24.04
